### ISSUE TITLE
msgpack serialization errors do not reset internal buffers

### ISSUE THREAD

**Issue by vEpiphyte** [msgpack/msgpack-python#258] opened 2017-11-14 19:45 UTC
If a serialization error occurs in a Packer object due to a invalid type being serialized, this does not clear the Packer's internal buffer.  This can lead to the situation where the reuse of a Packer object can cause extraneous data to be presented to a user.  Example code which demonstrates this behavior in both the cython packer and the fallback backer.

In addition, the cython packer and the fallback packer produce different messages in their TypeErrors.

```
import msgpack
import msgpack.fallback as m_fallback

pakr = msgpack.Packer(use_bin_type=True, encoding='utf8')
fallback_pakr = m_fallback.Packer(use_bin_type=True, encoding='utf8')
# Ensure we are testing both packer objects
assert type(pakr) != type(fallback_pakr)

packers = [pakr, fallback_pakr]

bad_tufo = (
    'hehe',
    {
        'k1': 1,
        'k2': set([1, 2])  # This is a set and cannot be serialized
    }
)

good_tufo = (
    'hehe',
    {
        'k1': 1,
        'k2': (1, 2)
    }
)

weird_tufo = (
    'hehe',
    {
        'k1': 1,
        'k2': (
            'hehe',
            {
                'k1': 1,
                'k2': (1, 2)
            }
        )
    }
)

for p in packers:
    try:
        buf = p.pack(bad_tufo)
    except TypeError as e:
        # cython and pure python packers have different error messages.
        assert "can't serialize" in str(e) or "Cannot serialize" in str(e)

ret = []
for p in packers:
    try:
        buf = p.pack(good_tufo)
        ret.append(buf)
    except Exception:
        raise

for buf in ret:
    obj = msgpack.unpackb(buf, encoding='utf8', use_list=False)
    # We have a unpacked object which is the combination of part of one object
    # and the entirety of a second object
    assert obj == weird_tufo
```

Is this the intended behavior of the Packer objects or a implementation error?  The documentation here http://msgpack-python.readthedocs.io/en/latest/api.html does not list any expected behavior one way or the other.

**Comment by methane** [comment] 2017-11-15 06:43
There are no "intended behavior".  I didn't think about it.  So you shouldn't think
packer object can be reused safely after exception.
Sadly, Packer's buffer management is complicated by features which are not used
by 99% users.  I don't have time and motivation about fixing it in this year.

And exception message is not stable.  It can be changed by good or bad reasons.
Do not rely on message.

**Comment by methane** [comment] 2017-12-21 12:30
duplicate of #210

**Closed by methane** 2017-12-21 12:30 UTC
