### ISSUE TITLE
Python fallback and C implementation have different API

### ISSUE THREAD

**Issue by rspeer** [msgpack/msgpack-python#483] opened 2021-09-02 21:39 UTC
This is a clarification of #437 to provide an example of what goes wrong. The C implementation and the Python fallback provide a different API with incompatible arguments, particularly surrounding `strict_map_key`.

This is with msgpack 1.0.2 installed and using the C implementation:

```
>>> msgpack.loads(b'\x81\x01\x02')
Traceback (most recent call last):
  File "<ipython-input-5-4a8146f34cd3>", line 1, in <module>
    msgpack.loads(b'\x81\x01\x02')
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
ValueError: int is not allowed for map key

>>> msgpack.loads(b'\x81\x01\x02', strict_map_key=False)
{1: 2}
```

I am aware of the README and why `strict_map_key` is necessary. But this is with msgpack 1.0.2 installed without the python3-dev package available, so it uses the pure-Python fallback:

```
>>> msgpack.loads(b'\x81\x01\x02')
{1: 2}

>>> msgpack.loads(b'\x81\x01\x02', strict_map_key=False)
Traceback (most recent call last):
  File "<ipython-input-5-8f71260b9509>", line 1, in <module>
    msgpack.loads(b'\x81\x01\x02', strict_map_key=False)
  File "/home/ubuntu/env/lib/python3.8/site-packages/msgpack/fallback.py", line 118, in unpackb
    unpacker = Unpacker(None, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'strict_map_key'
```

The pure-Python fallback does not understand the `strict_map_key` argument, and in fact acts like `strict_map_key=False`, while the C code supports the argument and defaults to `strict_map_key=True`.

There is no way to successfully load the map `{1: 2}` on both versions of the code except to try both and catch the error.

**Comment by methane** [comment] 2021-09-03 01:03
fallback has strict_map_key.
https://github.com/msgpack/msgpack-python/blob/8fb709f2e0438862020d8810fa70a81fb5dac7d4/msgpack/fallback.py#L255

Did you double check yoru environment uses the latest version?
Did you try to create fresh virtualenvironment?

**Comment by rspeer** [comment] 2021-09-03 14:30
In my example above, the problem was fixed when I uninstalled msgpack, installed the system python3-dev package, and reinstalled msgpack, which made it start using `msgpack._cmsgpack`.

I can also confirm that the problem doesn't occur when the bytes are fed directly to the Unpacker in `msgpack.fallback`.

However, when I installed msgpack in a new env on a new system -- this was within the past week and it said it was version 1.0.2 -- I got a version that used the fallback and did not understand `strict_map_key`.

No matter what I try now, when I reinstall msgpack, I get the `msgpack._cmsgpack` version. Can you point me to how it decides which version to install so I can try to reproduce what I originally had?

**Comment by methane** [comment] 2021-09-04 02:54
Since you can not provide steps to reproduce, I just close this. Your environment is fine for now.

**Closed by methane** 2021-09-04 02:54 UTC
