### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [msgpack/msgpack-python#442] opened 2020-11-02 08:55 UTC
**Summary**
Installing msgpack-python on aarch64 via pip using command "pip3 install msgpack-python" tries to build wheel from source code.

**Problem description**
msgpack-python doesn't have wheel for aarch64 on PyPI repository. So, while installing msgpack-python via pip on aarch64, pip builds wheel for same resulting in it takes more time to install msgpack-python. Making wheel available for aarch64 will benefit aarch64 users by minimizing msgpack-python installation time.

**Expected Output**
Pip should be able to download msgpack-python wheel from PyPI repository rather than building it from source code.

@msgpack-python-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make msgpack-python wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by methane** [comment] 2020-11-02 09:01
Don't send spam to massive amout repositories!
If you really want to ask arm64 wheel support, you must check existing issue before filing new issue.

Close this because duplicate of #440.

**Closed by methane** 2020-11-02 09:01 UTC
