### ISSUE TITLE
exception hierarchy and its future

### ISSUE THREAD

**Issue by ThomasWaldmann** [msgpack/msgpack-python#233] opened 2017-07-03 18:40 UTC
http://msgpack-python.readthedocs.io/en/latest/api.html#exceptions

For the upper layer(s) of the current msgpack exception hierarchy, it states that:
```
Deprecated. Use Exception instead to catch all exception during packing.
```
or
```
Deprecated. Use ValueError instead.
```

I am not sure why that is deprecated, for me this feels backwards.

There are quite a lot of normal use cases where one wants to catch all msgpack exceptions, but one can't just catch `Exception` (or `ValueError`).

For example, look at this, taken from borgbackup code:

```
try:
    with IntegrityCheckedFile(hints_path, write=False, integrity_data=integrity_data) as fd:
        hints = msgpack.unpack(fd)
except (msgpack.UnpackException, FileNotFoundError, FileIntegrityError) as e: 
    ... # the file is not there / is crap, rebuild it.
```

So, if I'ld use `Exception` there, it would also catch all sorts of unspecific issues in the `IntegrityCheckedFile` code - that's a bad idea.

Of course one could work around by having an additional inner try/except and reraise some specific custom exception, but why not just keep UnpackException for such cases?

**Comment by methane** [comment] 2017-07-20 09:54
First reason is I think using exception type for "where the error come from" is bad idea.
Exception type should be "what's kind of the error".

Second reason is I don't want to hide real exception.
Exception may be happen unexpected reason.
To guarantee unpack never raise Exceptions other than UnpackException, (1) check all code
carefully, or (2) catch all exception at top of `unpack()`, then throw away all important information and `raise UnpackException("something go wrong")`.
I don't want do both for performance and maintenance point of view.

So, currently, there are no guarantee `unapck()` always raise subclass of `UnpackException`.
If ValueError, TypeError or other exceptions are raised, I won't fix it.
That's why I declare it's "deprecated".

But I have no plan to remove `UnpackException` completely.

**Comment by jfolz** [comment] 2017-08-20 11:02
Well, if something is deprecated that usually means it will be removed at some point in the future.
As we can see in e.g. #239 the exception situation is not exactly brilliant right now.
The important question is: are custom exceptions actually useful? Do they really help developers recovering from errors they encounter during runtime?

What do you do when you encounter a `PackOverflowError`? Do you alter your data? Convert them to strings/ExtType? That's pretty awkward.
Does a `PackValueError` give any benefit over a standard `ValueError`?
`BufferFull` is just a `MemoryError` in disguise.
`OutOfData` and `ExtraData` mean your data is corrupt or incomplete. Or your code is wrong and more data than necessary is fed.

As libraries go msgpack is pretty straightforward. It takes Python objects and turns them into bytes and vice-versa. Unless you are unpacking messages from external sources, any exceptions you encounter are caused by programming errors in your code ("you're doing it wrong"™) or msgpack. Standard exceptions with meaningful message are sufficient to fix these.
If you do encounter corrupt messages recovery is mostly impossible anyway and it's the sender's responsibility to fix the problem.

**Comment by jfolz** [comment] 2017-08-20 11:15
For example take a look at numpy, an arguable much more complex and diverse library.
So far as I can tell they define one custom exception: [LinAlgError](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.LinAlgError.html#numpy.linalg.LinAlgError).
It's raised when your matrix doesn't fulfill a property required by some linear algebra operation.

For msgpack we could do something like this:

### Packing

- TypeError: we don't understand one of the objects, here's a repr of the offender
- ValueError: some value exceeds the msgpack specification (integer too low/high, string too long) or specified limits
- MemoryError: memory is full or limit reached

### Unpacking

- TypeError: we can't read message data from your object
- ValueError: message is malformed
- MemoryError: memory is full or limit reached

**Comment by ThomasWaldmann** [comment] 2017-08-21 04:41
@jfolz the point is **not** to somehow try to *recover* from a msgpack exception, but just to be able to differentiate exception sources and have more specific exception catching than `except Exception`.

I want to know `Was it msgpack that was blowing up?` (which is expected for corrupt input data)

Or was it IntegrityCheckedFile (or our code) blowing up with an unexpected exception (that would be a bug in our code as it is not expected to raise `ValueError` or any other unspecific Exception)?

See the code example at the end of the top post and the text below. **That** was my main point.

**Comment by jfolz** [comment] 2017-08-21 07:29
To fix bugs a descriptive error message and possibly a trace should suffice, right?
There's no guarantee that msgpack only ever raises msgpack-exceptions.
E.g., as demonstrated in #239, it may raise SystemException.

**Comment by ThomasWaldmann** [comment] 2017-08-21 08:33
I am speaking about exception processing, not humans looking at tracebacks.

And if we would catch `Exception` or `ValueError`, such a exception raised by our code would end up in the same handler. And I think it is no sane design to have to look into the message for automated processing.

**Comment by enkore** [comment] 2017-08-21 17:45
^ the main issue is error handling in loops.

```py
while True:
  data = fetch_data()
  unpacker.feed(data)
  try:
    for obj in unpacker:
      do_something(obj)
  except msgpack...:
      # corrupted input data
```

Works, mostly. This doesn't work with, say, ValueError or TypeError. To make it work under that circumstance:

```py
while True:
  data = fetch_data()
  unpacker.feed(data)
  while True:
    try:
       obj = next(unpacker)
    except ValueError, ... ,... ,... :
      # corrupted input data
    except StopIteration:
      break
    do_something(obj)
```

**Comment by methane** [comment] 2017-08-21 18:33
I don't like this code.  I don't want to maintain such code anymore: https://github.com/msgpack/msgpack-python/blob/f0f2c0b39703e0129d2352c71ec9811a8f275cc8/msgpack/_unpacker.pyx#L492-L493

I dislike wrapping exception. I believe
`UnicodeDecodeError('utf-8', b'\x82\xb1\x82\xf1\x82\xc9\x82\xbf\x82\xcd', 0, 1, 'invalid start byte')`
is better than
`UnpackValueError(UnicodeDecodeError('utf-8', b'\x82\xb1\x82\xf1\x82\xc9\x82\xbf\x82\xcd', 0, 1, 'invalid start byte'),)`

Python's json module doesn't wrap TypeError and ValueError:

```
>>> json.dumps(b"foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
>>> def hook(x): raise ValueError
... 
>>> json.loads('{"foo": "bar"}', object_pairs_hook=hook)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/inada-n/pyenv/versions/3.6.2/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "<stdin>", line 1, in hook
ValueError
```

Even if there are some case it's useful, I don't want to maintain it.
You can add thin wrapper layer to wrap exceptions.

**Comment by ThomasWaldmann** [comment] 2017-08-21 20:28
Well, of course you can (not) maintain what you like, but pushing the "write some wrapper" onto all N library users causes up to N times the work, not just once.

And also, if people do not write the wrappers, they might run into such exception handling issues as shown above.

**Comment by methane** [comment] 2017-08-22 01:37
I don't disagree.  I never need such an exception handler.

For web application, both of unpack error and `do_sometihng(unpacked)` error cause "500 Internal Server Error" and traceback is logged.
For scripts, both of errors cause stop the script with traceback.
I can see Traceback to know where the error comes from.
(And that's one of reasons why I don't like wrapping exception; it sometimes hide real traceback, especially on Python 2)

There are rare cases which need to distinguish where ValueError comes from with `except` clause.

**Comment by jfolz** [comment] 2017-08-22 10:08
That's also what I didn't really understand. I agree that looking at the error message to find out where it came from is a stupid idea. What happens in these except-blocks that needs to differentiate where, e.g., a `ValueError` originates? And if if makes a difference, why is there only one except-block?

@ThomasWaldmann's example handles three types of exceptions with the same except-block. If exceptions raised by msgpack need to be handled separately, a try-except block around unpack will do the job.

@enkore's example can have try-except around `do_something(obj)` as well. In this case you can keep iterating if you can recover from what happened in your code, or break if you can't. Iteration must stop when the `Unpacker` encounters a `ValueError` (it is in an invalid state). It will also stop on any exception in `do_something(obj)` since they are not handled inside the loop. Assuming `do_something(obj)` works correctly the cause is the same: invalid input data.

The overhead of a try-except block is about the same as a function call with one argument, so pretty negligible.
https://stackoverflow.com/questions/2522005/cost-of-exception-handlers-in-python
http://gerg.ca/blog/post/2015/try-except-speed/
https://ilovesymposia.com/2015/12/10/the-cost-of-a-python-function-call/

**Comment by enkore** [comment] 2017-08-22 10:22
> The overhead of a try-except block is about the same as a function call with one argument, so pretty negligible, and will most likely be more than offset by removing some now-unnecessary try-except blocks inside msgpack.

Exception handling is implemented very differently in Python and the C API (=Cython). In Python there are a couple extra opcodes to do this; in the C API a try:/except: translates to saving the current exception (try:/except: is possible inside another except: clause), executing the try block and jumping to the except: block (goto) if an error happens. Note that when using the C API, you always have to check for errors after every operation, so this makes virtually no difference.

That aside, this discussion hasn't been about performance so far and I don't really see the relevance.

**Comment by jfolz** [comment] 2017-08-22 11:37
I'm trying to understand your side of the argument and that's just my thought process working. I care about performance a lot and I tend to project that onto others ;)

What I gathered so far is that there are cases where it is necessary to know whether an exception was raised by msgpack or not. _Some_ (not all) packing/unpacking-related errors can currently be handled by catching msgpack-specific exceptions. If those go away additional try-except blocks around msgpack-calls or custom code will be necessary.

The other side of the argument is a concise and obvious exception policy and a reduction in complexity of msgpack code. I prefer libraries that don't surprise me with lots of different custom exceptions. Someone who just discovered msgpack will know immediately what a `ValueError` means, but might have to look up `ExtraData`. Or might get confused why he cannot easily deal with encoding problems, because `UnicodeDecodeError`s are wrapped in `UnpackValueError`s. Aligning msgpack's exception behavior with similar libraries (especially builtin json) will make it even more of a drop-in replacement.

**Comment by fake-name** [comment] 2017-09-17 04:46
> Use Exception instead to catch all exception during packing.

This *explicitly* contravenes general ["best-practices"](https://stackoverflow.com/questions/756180/pylint-warning-on-except-exception). 

Catching general `Exception` is problematic, because it can mask issues from other sources.

**Comment by methane** [comment] 2017-09-17 09:34
> Catching general Exception is problematic, because it can mask issues from other sources.

You will missed discussion.
Currently, we do it (mask all exception) in msgpack library.  And I want to stop it in the future.

**Comment by methane** [comment] 2018-10-03 08:58
I'm re-considering this, toward next msgpack version.

---

> Right now, If I want to catch exceptions that are thrown by this library, but _not_ system errors (out of memory, filesystem, etc...),

Why anyone want to catch "thrown by this library"?

For example, should I raise UnpackMemoryError instead of MemoryError, if malloc is called from msgpack library, and keep MemoryError raised from underlaying C API?

At least, I don't wrap MemoryError now and I don't want to do it too.
It's tottaly out-of-scope.

---

Examples in the issue body and https://github.com/msgpack/msgpack-python/issues/233#issuecomment-323807791 shows another reasoning.

They want to catch exception only while unpacking.  But I don't want to maintain wrapped exception (e.g. `UnpackValueError(UnicodeDecodeError('utf-8', b'\x82\xb1[snip]', 0, 1, 'invalid start byte'),)`)  for this reason.

Use narrow try-clause instead.

---

On the other hand, base exception class `UnpackException` for `OutOfData` and `BufferFull` is not bad.  It can be un-deprecated, and kept forever.
I should document "`unpack` may raise exceptions other than `UnpackException`" instead.

---

Again, I don't like error wrapping.
But `UnpackValueError` is used for corrupted msgpack format too.
I can keep `UnpackValueError` for this particular usage, but I don't like it's name.

I think `InvalidMsgpackSequence` may be better name for it.  It will extend `UnpackException` and `ValueError`.

When you want to catch all unexpected msgpack data (non-UTF8 str, or invalid msgpack sequence), you can catch just `ValueError`.

---

In case of Packing, packer returned raw `TypeError` already.  I want to remove all of `PackException`, `PackValueError` and `PackOverflowError`.

**Closed** 2018-11-09 13:13 UTC
